services:
  User.Api.controllers.UserGetController:
    class: ../../controller/User/UserGetController

  User.Api.controllers.UserPostController:
    class: ../../controller/User/UserPostController

  User.Api.controllers.UserPutController:
    class: ../../controller/User/UserPutController

  User.Context.infrastructure.UserRepository:
    class: ../../../../context/User/infrastructure/DrizzleUserRepository
    arguments: ['@Shared.Context.infrastructure.WinstonLogger']


  User.Context.application.UserCreator:
    class: ../../../../context/User/application/UserCreator
    arguments: ['@User.Context.infrastructure.UserRepository', '@Shared.Context.infrastructure.WinstonLogger']

  User.Context.application.UserUpdater:
    class: ../../../../context/User/application/UserUpdater
    arguments:
      [
        '@User.Context.infrastructure.UserRepository',
        '@User.Context.application.UserFinder',
        '@Shared.Context.infrastructure.WinstonLogger',
      ]

  User.Context.application.UserFinder:
    class: ../../../../context/User/application/UserFinder
    arguments: ['@User.Context.infrastructure.UserRepository', '@Shared.Context.infrastructure.WinstonLogger']
