imports:
  - { resource: ./Status/application.yaml }
  - { resource: ./User/application_dev.yaml }
  - { resource: ./Task/application_dev.yaml }
  - { resource: ./Project/application_dev.yaml }
  - { resource: ./Shared/application.yaml }
