imports:
  - { resource: ./Task/application_test.yaml }
  - { resource: ./User/application_test.yaml }
  - { resource: ./Status/application.yaml }
  - { resource: ./Project/application_test.yaml }
  - { resource: ./Shared/application.yaml }
